# Streamlit secrets configuration
# Longdo Maps API Configuration

LONGDO_API_KEY = "498a530031a9bb9eaf78eceac37d4e20"

# Additional configuration can be added here
# Keep this file secure and don't commit it to version control
